language: node_js
node_js:
- '12.22.12'
env:
  global:
  - GH_USER_EMAIL="jeremie.bertrand@gmail.com"
  - GH_USER_NAME="laedit"
  - DEPLOY_REPOSITORY="git@github.com:laedit/cozy-konnector-gazdestrasbourg.git"
  # Token to access Cozy Registry, you should replace it with a token specific to this konnector
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
# - yarn run check
# deploy:
# - provider: script
#   skip-cleanup: true
#   script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
#   on:
#     branch: master
# - provider: script
#   skip-cleanup: true
#   script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
#   on:
#     tags: true
before_install:
# - openssl aes-256-cbc -K $encrypted_35a3fe94e096_key -iv $encrypted_35a3fe94e096_iv
#   -in github_deploy_key.enc -out /tmp/github_deploy_key -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/github_deploy_key
# - ssh-add /tmp/github_deploy_key
after_deploy: 
# - rm /tmp/github_deploy_key
# - ssh-add -D
